import type { NextConfig } from "next";

const isProduction = process.env.NODE_ENV === "production";

const nextConfig: NextConfig = {
  async rewrites() {
    return [
      // Profile images (SEO-friendly aliases -> existing files)
      { source: '/images/rafal-ulatowski-profile-photo.png', destination: '/images/profile-photo.png' },
      { source: '/images/rafal-ulatowski-profile-photo.webp', destination: '/images/profile-photo.webp' },

      // Illustrations
      { source: '/images/azure-architecture-design.svg', destination: '/images/architecture-work.svg' },
      { source: '/images/azure-team-collaboration.svg', destination: '/images/team-work.svg' },
      { source: '/images/development-environment-workspace.svg', destination: '/images/workspace.svg' },
      { source: '/images/rafal-ulatowski-headshot.svg', destination: '/images/rafal-headshot.svg' },
      { source: '/images/rafal-ulatowski-professional.svg', destination: '/images/rafal-professional.svg' },
      { source: '/images/rafal-ulatowski-profile-illustration.svg', destination: '/images/rafal-profile.svg' },
      { source: '/images/rafal-ulatowski-realistic.svg', destination: '/images/rafal-realistic.svg' },
      // WebP aliases (generated by convert-images)
    ];
  }
  ,
  async headers() {
    const securityHeaders = {
      // Prevent clickjacking: allow framing only from same origin (more compatible)
      source: '/:path*',
      headers: [
        {
          key: 'X-Frame-Options',
          value: 'SAMEORIGIN',
        },
        {
          key: 'Content-Security-Policy',
          // frame-ancestors 'self' allows same-origin frames but blocks others
          value: "frame-ancestors 'self'",
        },
      ],
    };

    if (isProduction) {
      return [
        securityHeaders,
        {
          // cache static _next files long-term in production
          source: '/_next/static/:path*',
          headers: [
            {
              key: 'Cache-Control',
              value: 'public, max-age=31536000, immutable',
            },
          ],
        },
        {
          // cache image files (pre-converted WebP) long-term
          source: '/images/:path*',
          headers: [
            {
              key: 'Cache-Control',
              value: 'public, max-age=31536000, immutable',
            },
          ],
        },
        {
          // cache OG images for social media crawlers
          source: '/og/:path*',
          headers: [
            {
              key: 'Cache-Control',
              value: 'public, max-age=31536000, immutable',
            },
          ],
        },
      ];
    }

    return [
      securityHeaders,
      {
        source: '/_next/static/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'no-store',
          },
        ],
      },
      {
        source: '/images/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'no-cache',
          },
        ],
      },
      {
        source: '/og/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'no-cache',
          },
        ],
      },
    ];
  }
};

export default nextConfig;
